# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
